# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acor < Formula
  desc "Aho-Corasick multi-pattern string matching on Redis or Valkey"
  homepage "https://github.com/skyoo2003/acor"
  version "1.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skyoo2003/acor/releases/download/v1.6.0/acor_1.6.0_darwin_amd64.tar.gz"
      sha256 "3639fc7cd860b7d0b16e28ac707292c103720d87c7e8cc2eb319f19a70f44755"

      define_method(:install) do
        bin.install "acor"
        # A bottle contains the installed prefix, not the archive it was built from,
        # so the notices have to be installed to survive a `brew install`. Adding them
        # to archives.files above is not enough on its own.
        doc.install "LICENSE", "NOTICE"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skyoo2003/acor/releases/download/v1.6.0/acor_1.6.0_darwin_arm64.tar.gz"
      sha256 "5f3e831ec3b6e1f31f96003e412d9084524d891c4f003ee353012fea308c585a"

      define_method(:install) do
        bin.install "acor"
        # A bottle contains the installed prefix, not the archive it was built from,
        # so the notices have to be installed to survive a `brew install`. Adding them
        # to archives.files above is not enough on its own.
        doc.install "LICENSE", "NOTICE"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/acor/releases/download/v1.6.0/acor_1.6.0_linux_amd64.tar.gz"
      sha256 "f98f66914ff00a1ae9c5e01f0408cb5d186f3d220fdbe681b1a9084024e943d8"
      define_method(:install) do
        bin.install "acor"
        # A bottle contains the installed prefix, not the archive it was built from,
        # so the notices have to be installed to survive a `brew install`. Adding them
        # to archives.files above is not enough on its own.
        doc.install "LICENSE", "NOTICE"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/acor/releases/download/v1.6.0/acor_1.6.0_linux_arm64.tar.gz"
      sha256 "dde8f9bcefbb33d66ed2b7a204e9b430b057bcf8f8f959d25bfdc2641fbd9419"
      define_method(:install) do
        bin.install "acor"
        # A bottle contains the installed prefix, not the archive it was built from,
        # so the notices have to be installed to survive a `brew install`. Adding them
        # to archives.files above is not enough on its own.
        doc.install "LICENSE", "NOTICE"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/acor version")
    assert_match "Usage:", shell_output("#{bin}/acor 2>&1", 2)
  end
end
