# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acor < Formula
  desc "Aho-Corasick multi-pattern string matching on Redis or Valkey"
  homepage "https://github.com/skyoo2003/acor"
  version "0.11.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skyoo2003/acor/releases/download/v0.11.0/acor_0.11.0_darwin_amd64.tar.gz"
      sha256 "c8cc1f78d27efce95539d51140a43d208364100cc5dea28cd0840e7e9dd2d274"

      define_method(:install) do
        bin.install "acor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skyoo2003/acor/releases/download/v0.11.0/acor_0.11.0_darwin_arm64.tar.gz"
      sha256 "cc7595126ae669d5e2598b3384ccd08504114cfc839bb4f8340719086561bf6f"

      define_method(:install) do
        bin.install "acor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/acor/releases/download/v0.11.0/acor_0.11.0_linux_amd64.tar.gz"
      sha256 "05d5f701aee3af28cc99f73ca22abc1218f8ee06f36d9ffa4327ebee77c6bd5c"
      define_method(:install) do
        bin.install "acor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/acor/releases/download/v0.11.0/acor_0.11.0_linux_arm64.tar.gz"
      sha256 "0c0e47fa3fe88b346f7f6ebd068af21762cf0cbc52a7f5196e530741be0890fe"
      define_method(:install) do
        bin.install "acor"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/acor version")
    assert_match "Usage:", shell_output("#{bin}/acor 2>&1", 2)
  end
end
