# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devcloud < Formula
  desc "Local development companion for cloud-native apps"
  homepage "https://github.com/skyoo2003/devcloud"
  version "1.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skyoo2003/devcloud/releases/download/v1.1.1/devcloud_1.1.1_darwin_amd64.tar.gz"
      sha256 "e5e3b8861f97d8948ede821a46fd03afc848ddced6bf588702c1fdcb79f4634c"

      define_method(:install) do
        bin.install "devcloud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skyoo2003/devcloud/releases/download/v1.1.1/devcloud_1.1.1_darwin_arm64.tar.gz"
      sha256 "f924d6c2686f08e91c71bd71e6295cdff298564bb0529c1f58dd381f80cccfbf"

      define_method(:install) do
        bin.install "devcloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/devcloud/releases/download/v1.1.1/devcloud_1.1.1_linux_amd64.tar.gz"
      sha256 "93fee6000a040d1a0df2b8859ecffa059da86568ae8f71ec0772c6a348c6eb64"
      define_method(:install) do
        bin.install "devcloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/devcloud/releases/download/v1.1.1/devcloud_1.1.1_linux_arm64.tar.gz"
      sha256 "0552e50cdc9654420589daffb8ee9c37a0d5b20787f423a686fb8b99b7f9a8f5"
      define_method(:install) do
        bin.install "devcloud"
      end
    end
  end

  test do
    assert_match "-config", shell_output("#{bin}/devcloud -h 2>&1")
  end
end
