# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devcloud < Formula
  desc "Local development companion for cloud-native apps"
  homepage "https://github.com/skyoo2003/devcloud"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skyoo2003/devcloud/releases/download/v1.0.0/devcloud_1.0.0_darwin_amd64.tar.gz"
      sha256 "6eb4c384ef0bbf12fec63174582b9a9224bf8df962b0fd28eb0187c7bdbf87bb"

      define_method(:install) do
        bin.install "devcloud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skyoo2003/devcloud/releases/download/v1.0.0/devcloud_1.0.0_darwin_arm64.tar.gz"
      sha256 "cede8e4abaa23802ab8e8a15c4ebd25e4062d7f8e8445c6d8166260b3c5e6b22"

      define_method(:install) do
        bin.install "devcloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/devcloud/releases/download/v1.0.0/devcloud_1.0.0_linux_amd64.tar.gz"
      sha256 "ed86e2aa72dcad883327c24dbd3350bf857ae6ec5a48a84c3bda34b59e12d9b7"
      define_method(:install) do
        bin.install "devcloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/devcloud/releases/download/v1.0.0/devcloud_1.0.0_linux_arm64.tar.gz"
      sha256 "eea1d50c6d996271be110b30bb03e680a75b0427363d3f7b5a0aa3d3da22b8a3"
      define_method(:install) do
        bin.install "devcloud"
      end
    end
  end

  test do
    assert_match "-config", shell_output("#{bin}/devcloud -h 2>&1")
  end
end
