# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devcloud < Formula
  desc "Local development companion for cloud-native apps"
  homepage "https://github.com/skyoo2003/devcloud"
  version "1.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skyoo2003/devcloud/releases/download/v1.3.0/devcloud_1.3.0_darwin_amd64.tar.gz"
      sha256 "8c68484695b26eb3dfdb89c5b4e9b3e8ae419438042fe1210b370ae787d1cb8f"

      define_method(:install) do
        bin.install "devcloud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skyoo2003/devcloud/releases/download/v1.3.0/devcloud_1.3.0_darwin_arm64.tar.gz"
      sha256 "6620edfa65773b112a97dd60fa50451f497de349424f524eaba11f4582b0ac0c"

      define_method(:install) do
        bin.install "devcloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/devcloud/releases/download/v1.3.0/devcloud_1.3.0_linux_amd64.tar.gz"
      sha256 "ef2e736d6bc61aad3b4153d793acab80419826cdd111e976e1e109fa2daa08fc"
      define_method(:install) do
        bin.install "devcloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/devcloud/releases/download/v1.3.0/devcloud_1.3.0_linux_arm64.tar.gz"
      sha256 "31f9ff7eeac528bab466ec4888fa96dc41cb8af2c02484e33434ab09d68ac5d0"
      define_method(:install) do
        bin.install "devcloud"
      end
    end
  end

  test do
    assert_match "-config", shell_output("#{bin}/devcloud -h 2>&1")
  end
end
