# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kvs < Formula
  desc "A simple key-value store"
  homepage "https://github.com/skyoo2003/kvs"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skyoo2003/kvs/releases/download/v0.1.1/kvs_0.1.1_darwin_amd64.tar.gz"
      sha256 "d3263cc241c5dc00ff160fa4a43783deacb93604b383445df678f0479cbff0af"

      define_method(:install) do
        bin.install "kvs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skyoo2003/kvs/releases/download/v0.1.1/kvs_0.1.1_darwin_arm64.tar.gz"
      sha256 "a33001605d146e266e1ea436285bc021901ecda5d05b5ab1c526ba3ce0eae53b"

      define_method(:install) do
        bin.install "kvs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/kvs/releases/download/v0.1.1/kvs_0.1.1_linux_amd64.tar.gz"
      sha256 "3efd204cc42fd56d44784eb93a5ff86982eef9467676a176cacd24b9a9435ec1"
      define_method(:install) do
        bin.install "kvs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/kvs/releases/download/v0.1.1/kvs_0.1.1_linux_arm64.tar.gz"
      sha256 "1aee43c6b009e78cc8720a401edc0db8ef9bd107a2514ea9223a718287095ca6"
      define_method(:install) do
        bin.install "kvs"
      end
    end
  end

  test do
    system "#{bin}/kvs -v"
  end
end
