# This file was generated by GoReleaser. DO NOT EDIT.
cask "kvs" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "140f7da48ef7212d4fcfa84cbc36dd6b972a784642a8fd5ab23ab1d517b1cdeb"
      url "https://github.com/skyoo2003/kvs/releases/download/v#{version}/kvs_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e104ea38686c061bd129522a833a4063795834315026e41a3481d5283ff04748"
      url "https://github.com/skyoo2003/kvs/releases/download/v#{version}/kvs_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "83a27b1a546854d05ebad7285118f378a66fa30538c0f486bea21811b69e62ce"
      url "https://github.com/skyoo2003/kvs/releases/download/v#{version}/kvs_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5189019e4b5f13dd4c0c6edc9eeeb9d59eae911ca6322ce124986cf8e92afc0c"
      url "https://github.com/skyoo2003/kvs/releases/download/v#{version}/kvs_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kvs"
  desc "A key-value store you can run as a server or import as a Go module"
  homepage "https://github.com/skyoo2003/kvs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kvs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kvs"]
    end
  end

  # No zap stanza required

end
