# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acor < Formula
  desc "Aho-Corasick automaton working On Redis/Valkey"
  homepage "https://github.com/skyoo2003/acor"
  version "0.10.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skyoo2003/acor/releases/download/v0.10.1/acor_0.10.1_darwin_amd64.tar.gz"
      sha256 "b01f3005b43ae20a2f2a0f606548e0628a9fda1d205c6a5868ae9997ba2b352e"

      define_method(:install) do
        bin.install "acor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skyoo2003/acor/releases/download/v0.10.1/acor_0.10.1_darwin_arm64.tar.gz"
      sha256 "29da38b485147d1ef2f458ac747a2a7b52e235e2d2c432c2c66cd23a1a5c75c4"

      define_method(:install) do
        bin.install "acor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/acor/releases/download/v0.10.1/acor_0.10.1_linux_amd64.tar.gz"
      sha256 "0e61a0287af9244df34cfa5e4f18777aa2f50eea55273eaf3bdf0b53ca5f8b4e"
      define_method(:install) do
        bin.install "acor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/acor/releases/download/v0.10.1/acor_0.10.1_linux_arm64.tar.gz"
      sha256 "264a8785b3c200ca0ecbdcb5043e79272072157a7f372ab21714b45f8a9584f0"
      define_method(:install) do
        bin.install "acor"
      end
    end
  end

  test do
    assert_match "Usage:", shell_output("#{bin}/acor 2>&1", 2)
  end
end
