# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devcloud < Formula
  desc "Local development companion for cloud-native apps"
  homepage "https://github.com/skyoo2003/devcloud"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skyoo2003/devcloud/releases/download/v0.2.0/devcloud_0.2.0_darwin_amd64.tar.gz"
      sha256 "d5c3789614aea3043b6f02c3ccd871316a2d5d724ef0c632a414fda22314c429"

      define_method(:install) do
        bin.install "devcloud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skyoo2003/devcloud/releases/download/v0.2.0/devcloud_0.2.0_darwin_arm64.tar.gz"
      sha256 "c6e5a154cd9063b13d452afb8a3055c357a9a1388f01efae3dab5d3378ef39d5"

      define_method(:install) do
        bin.install "devcloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/devcloud/releases/download/v0.2.0/devcloud_0.2.0_linux_amd64.tar.gz"
      sha256 "95e7b7620de3d470de25c995897e9df1334e64fe52c5b329b5d84509bcb2cbe3"
      define_method(:install) do
        bin.install "devcloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyoo2003/devcloud/releases/download/v0.2.0/devcloud_0.2.0_linux_arm64.tar.gz"
      sha256 "0b4b41a07c8eb08e92ab237bbb38620ac03ca44241df6cc07c96b8c4ab692495"
      define_method(:install) do
        bin.install "devcloud"
      end
    end
  end

  test do
    assert_match "-config", shell_output("#{bin}/devcloud -h 2>&1")
  end
end
